steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/rosy-ratio-438620-f8/poorva-100934359/app:$COMMIT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rosy-ratio-438620-f8/poorva-100934359/app:$COMMIT_SHA']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
